"""
Base repository containing reusable database operations.

Every PostgreSQL repository should inherit from this class.
"""

from __future__ import annotations

from typing import Generic
from typing import TypeVar

from loguru import logger
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.ext.asyncio import AsyncSession

TModel = TypeVar("TModel")


class BaseRepository(Generic[TModel]):
    """
    Provides common database operations for repositories.

    This class is intentionally persistence-focused.
    It should never contain business logic.
    """

    def __init__(self, session: AsyncSession) -> None:
        """
        Initialize repository.

        Args:
            session:
                SQLAlchemy async session.
        """

        self._session = session

    @property
    def session(self) -> AsyncSession:
        """
        Expose session to child repositories.
        """

        return self._session

    async def add(
        self,
        model: TModel,
    ) -> None:
        """
        Stage a model for insertion.

        NOTE:
        This does NOT commit the transaction.
        """

        self._session.add(model)

    async def delete(
        self,
        model: TModel,
    ) -> None:
        """
        Stage a model for deletion.

        NOTE:
        This does NOT commit the transaction.
        """

        await self._session.delete(model)

    async def flush(self) -> None:
        """
        Flush pending SQL statements to the database.

        Useful when IDs generated by the database
        are needed before commit.
        """

        await self._session.flush()

    async def refresh(
        self,
        model: TModel,
    ) -> None:
        """
        Refresh object from database.
        """

        await self._session.refresh(model)

    async def commit(self) -> None:
        """
        Commit current transaction.
        """

        try:

            await self._session.commit()

        except SQLAlchemyError:

            logger.exception("Database commit failed.")

            await self.rollback()

            raise

    async def rollback(self) -> None:
        """
        Roll back current transaction.
        """

        logger.warning("Rolling back current transaction.")

        await self._session.rollback()
